{
 "title": "billboard_status",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "billboard" },
   { "name": "mode" }
  ]
 },
 "panels": [
  {
   "title": "Country",
   "type": "stat",
   "targets": [
    {
     "measurement": "billboard_status",
     "query": "SELECT last(\"country\") FROM \"billboard_status\" WHERE ( ('' =~ /^$billboard$/) OR (\"billboard_id\" =~ /^$billboard$/) ) AND ( ('' =~ /^$mode$/) OR (\"mode\" =~ /^$mode$/) ) AND $timeFilter",
     "select": [
      [
       { "params": [ "country" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Timezone",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "billboard_status",
     "query": "SELECT mean(\"timezone\") FROM \"billboard_status\" WHERE ( ('' =~ /^$billboard$/) OR (\"billboard_id\" =~ /^$billboard$/) ) AND ( ('' =~ /^$mode$/) OR (\"mode\" =~ /^$mode$/) ) AND $timeFilter",
     "select": [
      [
       { "params": [ "timezone" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sunrise",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 0 },
   "targets": [
    {
     "measurement": "billboard_status",
     "query": "SELECT last(\"sunrise\") FROM \"billboard_status\" WHERE ( ('' =~ /^$billboard$/) OR (\"billboard_id\" =~ /^$billboard$/) ) AND ( ('' =~ /^$mode$/) OR (\"mode\" =~ /^$mode$/) ) AND $timeFilter",
     "select": [
      [
       { "params": [ "sunrise" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sunset",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "measurement": "billboard_status",
     "query": "SELECT last(\"sunset\") FROM \"billboard_status\" WHERE ( ('' =~ /^$billboard$/) OR (\"billboard_id\" =~ /^$billboard$/) ) AND ( ('' =~ /^$mode$/) OR (\"mode\" =~ /^$mode$/) ) AND $timeFilter",
     "select": [
      [
       { "params": [ "sunset" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Weather",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "measurement": "billboard_status",
     "query": "SELECT last(\"weather\") FROM \"billboard_status\" WHERE ( ('' =~ /^$billboard$/) OR (\"billboard_id\" =~ /^$billboard$/) ) AND ( ('' =~ /^$mode$/) OR (\"mode\" =~ /^$mode$/) ) AND $timeFilter",
     "select": [
      [
       { "params": [ "weather" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "measurement": "billboard_status",
     "query": "SELECT last(\"temp_C\") FROM \"billboard_status\" WHERE ( ('' =~ /^$billboard$/) OR (\"billboard_id\" =~ /^$billboard$/) ) AND ( ('' =~ /^$mode$/) OR (\"mode\" =~ /^$mode$/) ) AND $timeFilter",
     "select": [
      [
       { "params": [ "temp_C" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature Graph",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "billboard_status",
     "query": "SELECT mean(\"temp_C\") as temp FROM \"billboard_status\" WHERE ( ('' =~ /^$billboard$/) OR (\"billboard_id\" =~ /^$billboard$/) ) AND ( ('' =~ /^$mode$/) OR (\"mode\" =~ /^$mode$/) ) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp_C" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sound Graph",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "billboard_status",
     "query": "SELECT mean(\"sound_dB\") as sound FROM \"billboard_status\" WHERE ( ('' =~ /^$billboard$/) OR (\"billboard_id\" =~ /^$billboard$/) ) AND ( ('' =~ /^$mode$/) OR (\"mode\" =~ /^$mode$/) ) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "sound_dB" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind Speed Graph",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "velocitykmh" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "billboard_status",
     "query": "SELECT mean(\"wind_speed\") as windspeed FROM \"billboard_status\" WHERE ( ('' =~ /^$billboard$/) OR (\"billboard_id\" =~ /^$billboard$/) ) AND ( ('' =~ /^$mode$/) OR (\"mode\" =~ /^$mode$/) ) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "wind_speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}