{
 "title": "person",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "ad" },
   { "name": "mode" }
  ]
 },
 "panels": [
  {
   "title": "Person count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "15m" ], "type": "time" }
     ],
     "measurement": "person",
     "query": "SELECT count(\"billboard_id\") FROM \"person\" WHERE ( ('' =~ /^$ad$/) OR (\"ad_id\" =~ /^$ad$/) ) AND ( ('' =~ /^$mode$/) OR (\"mode\" =~ /^$mode$/) ) AND $timeFilter GROUP BY time(30m)",
     "select": [
      [
       { "params": [ "person_age" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Age",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "measurement": "person",
     "query": "SELECT count(\"billboard_id\") AS adult FROM \"person\" WHERE ( ('' =~ /^$ad$/) OR (\"ad_id\" =~ /^$ad$/) ) AND ( ('' =~ /^$mode$/) OR (\"mode\" =~ /^$mode$/) ) AND (\"person_age\" = 'ADULT')  AND $timeFilter",
     "select": [
      [
       { "params": [ "person_age" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "person_age", "operator": "=", "value": "ADULT" }
     ]
    },
    {
     "measurement": "person",
     "query": "SELECT count(\"billboard_id\") AS child FROM \"person\" WHERE ( ('' =~ /^$ad$/) OR (\"ad_id\" =~ /^$ad$/) ) AND ( ('' =~ /^$mode$/) OR (\"mode\" =~ /^$mode$/) ) AND (\"person_age\" = 'CHILD') AND $timeFilter",
     "select": [
      [
       { "params": [ "person_age" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "person_age", "operator": "=", "value": "YOUNG" }
     ]
    },
    {
     "measurement": "person",
     "query": "SELECT count(\"billboard_id\") AS baby FROM \"person\" WHERE ( ('' =~ /^$ad$/) OR (\"ad_id\" =~ /^$ad$/) ) AND ( ('' =~ /^$mode$/) OR (\"mode\" =~ /^$mode$/) ) AND (\"person_age\" = 'BABY') AND $timeFilter",
     "select": [
      [
       { "params": [ "person_age" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "person_age", "operator": "=", "value": "YOUNG" }
     ]
    },
    {
     "measurement": "person",
     "query": "SELECT count(\"billboard_id\") AS elder FROM \"person\" WHERE ( ('' =~ /^$ad$/) OR (\"ad_id\" =~ /^$ad$/) ) AND ( ('' =~ /^$mode$/) OR (\"mode\" =~ /^$mode$/) ) AND (\"person_age\" = 'ELDER') AND $timeFilter",
     "select": [
      [
       { "params": [ "person_age" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "person_age", "operator": "=", "value": "YOUNG" }
     ]
    }
   ]
  },
  {
   "title": "Gender",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "measurement": "person",
     "query": "SELECT count(\"billboard_id\") AS man FROM \"person\" WHERE ( ('' =~ /^$ad$/) OR (\"ad_id\" =~ /^$ad$/) ) AND ( ('' =~ /^$mode$/) OR (\"mode\" =~ /^$mode$/) ) AND (\"person_gender\" = 'MAN') AND $timeFilter",
     "select": [
      [
       { "params": [ "person_age" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "person_gender", "operator": "=", "value": "MAN" }
     ]
    },
    {
     "measurement": "person",
     "query": "SELECT count(\"billboard_id\") AS woman FROM \"person\" WHERE ( ('' =~ /^$ad$/) OR (\"ad_id\" =~ /^$ad$/) ) AND ( ('' =~ /^$mode$/) OR (\"mode\" =~ /^$mode$/) ) AND (\"person_gender\" = 'WOMAN') AND $timeFilter",
     "select": [
      [
       { "params": [ "person_age" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "person_gender", "operator": "=", "value": "WOMAN" }
     ]
    }
   ]
  }
 ]
}